// scripts/generate-verse-data.ts
// Usage: npx tsx scripts/generate-verse-data.ts
import * as fs from "fs";
import * as path from "path";

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "frontend", "src", "lib", "quran", "verseData.ts");

function parseCSV(filePath: string): Record<string, string>[] {
  const raw = fs.readFileSync(filePath, "utf-8").replace(/^\uFEFF/, "");
  const lines = raw.split(/\r?\n/).filter(Boolean);
  const headers = lines[0].split(",").map((h) => h.trim());
  return lines.slice(1).map((line) => {
    const parts = line.split(",");
    const record: Record<string, string> = {};
    headers.forEach((h, i) => {
      record[h] = (parts[i] ?? "").trim().replace(/^"|"$/g, "");
    });
    return record;
  });
}

const verseRows = parseCSV(path.join(ROOT, "verses.csv"));
const surahRows = parseCSV(path.join(ROOT, "surahs.csv"));

const verseLines = verseRows.map((r) => {
  const beginVerse = r["begin_verse"].replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return (
    `  { surahId:${r["surah_id"]}, ayah:${r["order_in_surah"]}, ` +
    `orderInQuran:${r["order_in_quraan"]}, reverseIndex:${r["reverse_index"]}, ` +
    `pageNo:${r["page_no"]}, lettersCount:${r["letters_count"]}, ` +
    `weightOnPage:${r["weight_on_page"]}, beginVerse:"${beginVerse}" }`
  );
});

const surahLines = surahRows.map((r) => {
  const name = r["name"].replace(/"/g, '\\"');
  return `  { id:${r["surah_id"]}, name:"${name}", ayahCount:${r["no_verses"]} }`;
});

const output = `// AUTO-GENERATED by scripts/generate-verse-data.ts — do not edit manually.
// Re-run if verses.csv or surahs.csv changes.

export interface VerseEntry {
  surahId: number;
  ayah: number;
  orderInQuran: number;
  reverseIndex: number;
  pageNo: number;
  lettersCount: number;
  weightOnPage: number;
  beginVerse: string;
}

export interface SurahData {
  id: number;
  name: string;
  ayahCount: number;
}

export const VERSES: VerseEntry[] = [
${verseLines.join(",\n")},
];

export const SURAHS_DATA: SurahData[] = [
${surahLines.join(",\n")},
];

export const BY_POSITION: Record<number, Record<number, VerseEntry>> = (() => {
  const m: Record<number, Record<number, VerseEntry>> = {};
  for (const v of VERSES) {
    if (!m[v.surahId]) m[v.surahId] = {};
    m[v.surahId][v.ayah] = v;
  }
  return m;
})();

export const BY_REVERSE: VerseEntry[] = [...VERSES].sort(
  (a, b) => a.reverseIndex - b.reverseIndex
);

export const REVERSE_IDX_TO_ARRAY_IDX: Record<number, number> = (() => {
  const m: Record<number, number> = {};
  BY_REVERSE.forEach((v, i) => { m[v.reverseIndex] = i; });
  return m;
})();
`;

// ── Validate weight_on_page sums per page ───────────────────────────────────
const pageWeights: Record<number, number> = {};
for (const r of verseRows) {
  const page = Number(r["page_no"]);
  pageWeights[page] = (pageWeights[page] ?? 0) + Number(r["weight_on_page"]);
}
let validationErrors = 0;
for (const [page, sum] of Object.entries(pageWeights)) {
  if (sum < 0.99 || sum > 1.01) {
    console.error(`ERROR: page ${page} weight sum = ${sum.toFixed(6)} (expected ~1.0)`);
    validationErrors++;
  }
}
if (validationErrors > 0) {
  console.error(`Aborting: ${validationErrors} page(s) have invalid weight sums. Fix verses.csv before regenerating.`);
  process.exit(1);
}
console.log(`Weight validation passed: all ${Object.keys(pageWeights).length} pages sum to ~1.0`);

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, output, "utf-8");
console.log(`Written ${verseRows.length} verses, ${surahRows.length} surahs → ${OUT}`);
